apiVersion: v1
kind: Service
metadata:
  name: happy-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: happy-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: happy-postgres
  template:
    metadata:
      labels:
        app: happy-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: happy
            - name: POSTGRES_PASSWORD
              value: happy
            - name: POSTGRES_DB
              value: happy
